apiVersion: v1
kind: Service
metadata:
  name: {{ include "noderediotaddon.fullname" . }}
  labels:
    {{- include "noderediotaddon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  externalTrafficPolicy: Local
  selector:
    {{- include "noderediotaddon.selectorLabels" . | nindent 4 }}
