{{- if .Values.bindServices.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls-properties
type: opaque
data:
  clientKeyStore: {{ .Values.iot.edge.clientKeyStore }}
  clientKeyStorePassword: "{{ .Values.iot.edge.clientKeyStorePassword | b64enc}}"
  clientTrustStore: {{ .Values.iot.edge.clientTrustStore }}
  clientTrustStorePassword: {{ .Values.iot.edge.clientTrustStorePassword | b64enc }}
{{- end}}
