apiVersion: v1
kind: Service
metadata:
  name: {{ include "customservice.fullname" . }}
  labels:
    {{- include "customservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  externalTrafficPolicy: Local
  selector:
    {{- include "customservice.selectorLabels" . | nindent 4 }}
