apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: ext-service-policy
spec: 
  podSelector: 
    matchLabels: 
      component: {{ include "helm.name" . }}
  ingress: 
    - from: 
        - ipBlock: 
            cidr: 0.0.0.0/0
        - podSelector: {}
        - namespaceSelector: {}
      ports: 
        - port: {{ .Values.service.port }}